const stats = require('./stats.js')
const setGame = require('./setgame.js')
const setAvatar = require('./setavatar.js')
const setUsername = require('./setusername.js')
const pingMe = require('./pingme.js')
const blacklist = require('./blacklist.js')
const unblacklist = require('./unblacklist.js')
const refresh = require('./refresh.js')
const getSources = require('./getsources.js')
const feedGuild = require('./feedguild.js')
const cleanFailed = require('./cleanfailed.js')
const forceRemove = require('./forceremove.js')
const debug = require('./debug.js')
const undebug = require('./undebug.js')
const setOverride = require('./setoverride.js')
const removeOverride = require('./removeoverride.js')
const allowCookies = require('./allowcookies.js')
const disallowCookies = require('./disallowcookies.js')
const setConfig = require('./setconfig.js')
const checkLimits = require('./checklimits.js')

exports.stats = stats
exports.setgame = setGame
exports.setavatar = setAvatar
exports.setusername = setUsername
exports.pingme = pingMe
exports.blacklist = blacklist
exports.unblacklist = unblacklist
exports.refresh = refresh
exports.getsources = getSources
exports.feedguild = feedGuild
exports.cleanfailed = cleanFailed
exports.forceremove = forceRemove
exports.debug = debug
exports.undebug = undebug
exports.setoverride = setOverride
exports.removeoverride = removeOverride
exports.allowcookies = allowCookies
exports.disallowcookies = disallowCookies
exports.setconfig = setConfig
exports.checklimits = checkLimits
