exports.inputRemoveRole = require('./inputRemoveRole.js')
exports.removeAllSuccess = require('./removeAllSuccess.js')
exports.removeDirectSuccess = require('./removeDirectSuccess.js')
exports.removeRoleSuccess = require('./removeRoleSuccess.js')
exports.selectAction = require('./selectAction.js')
exports.selectFeed = require('./selectFeed.js')
