export const GET_FEEDS = {
  prefix: 'GET_FEEDS',
  BEGIN: 'GET_FEEDS_BEGIN',
  SUCCESS: 'GET_FEEDS_SUCCESS',
  FAILURE: 'GET_FEEDS_FAILURE'
}

export const GET_ARTICLES = {
  prefix: 'GET_ARTICLES',
  BEGIN: 'GET_ARTICLES_BEGIN',
  SUCCESS: 'GET_ARTICLES_SUCCESS',
  FAILURE: 'GET_ARTICLES_FAILURE'
}

export const SET_ACTIVE_FEED = 'SET_ACTIVE_FEED'
