export enum FeedCloneProperties {
  MESSAGE = "MESSAGE",
  FITLERS = "FILTERS",
  MISC_OPTIONS = "MISC_OPTIONS",
  COMPARISONS = "COMPARISONS",
  REGEXOPS = "REGEXOPS",
  WEBHOOK = "WEBHOOK",
  SUBSCRIBERS = "SUBSCRIBERS",
}
