services:
  redis:
    image: redis:6-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs: /var/lib/redis/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs: /var/lib/rabbitmq/data
    expose:
      - 5672
  pg:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    tmpfs: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./src/mikro-orm.config.ts:/usr/src/app/mikro-orm.config.ts
      - ./migrations:/usr/src/app/migrations
    environment:
      - NODE_ENV=test
      - USER_FEEDS_POSTGRES_URI=postgres://postgres:postgres@pg:5432
      - USER_FEEDS_POSTGRES_DATABASE=test
      - USER_FEEDS_REDIS_URI=redis://redis:6379
      - USER_FEEDS_DISCORD_RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - USER_FEEDS_RABBITMQ_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      # - LOG_LEVEL=debug
    tty: true
    command: ${TEST_COMMAND}
