export enum InteractionTask {
  LIST_FEEDS = 'LIST_FEEDS',
  REMOVE_FEED = 'REMOVE_FEED',
  ON_CLICK_PREVIOUS_PAGE = 'ON_CLICK_PREVIOUS_PAGE',
  ON_CLICK_NEXT_PAGE = 'ON_CLICK_NEXT_PAGE',
  ADD_USER_FEED_SUBSCRIBER = 'ADD_FEED_USUBSCRIBER',
  REMOVE_USER_FEED_SUBSCRIBER = 'REMOVE_FEED_USUBSCRIBER',
}
