export enum DeliveryLogStatus {
  DELIVERED = "DELIVERED",
  PENDING_DELIVERY = "PENDING_DELIVERY",
  FAILED = "FAILED",
  REJECTED = "REJECTED",
  FILTERED_OUT = "FILTERED_OUT",
  MEDIUM_RATE_LIMITED = "MEDIUM_RATE_LIMITED",
  ARTICLE_RATE_LIMITED = "ARTICLE_RATE_LIMITED",
  PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED",
}
