export default {
  title: 'title',
  description: 'description',
  url: 'url',
  color: 'color',
  timestamp: 'timestamp',
  footerIconUrlCamelCase: 'footerIconUrl',
  footerIconUrl: 'footer_icon_url',
  footerTextCamelCase: 'footerText',
  footerText: 'footer_text',
  authorIconUrlCamelCase: 'authorIconUrl',
  authorIconUrl: 'author_icon_url',
  authorNameCamelCase: 'authorName',
  authorName: 'author_name',
  authorUrlCamelCase: 'authorUrl',
  authorUrl: 'author_url',
  thumbnailUrlCamelCase: 'thumbnailUrl',
  thumbnailUrl: 'thumbnail_url',
  imageUrlCamelCase: 'imageUrl',
  imageUrl: 'image_url'
}
